/* STATUS */
export const STATUS_TOGGLE_MODAL = "STATUS_TOGGLE_MODAL";
export const STATUS_GET_LIST = "STATUS_GET_LIST";
export const STATUS_GET_LIST_SUCCESS = "STATUS_GET_LIST_SUCCESS";
export const STATUS_GET_LIST_ERROR = "STATUS_GET_LIST_ERROR";
export const STATUS_ADD_ITEM = "STATUS_ADD_ITEM";
export const STATUS_ADD_ITEM_SUCCESS = "STATUS_ADD_ITEM_SUCCESS";
export const STATUS_ADD_ITEM_ERROR = "STATUS_ADD_ITEM_ERROR";
export const STATUS_UPDATE_ITEM = "STATUS_UPDATE_ITEM";
export const STATUS_UPDATE_ITEM_SUCCESS = "STATUS_UPDATE_ITEM_SUCCESS";
export const STATUS_UPDATE_ITEM_ERROR = "STATUS_UPDATE_ITEM_ERROR";
export const STATUS_DELETE_ITEM = "STATUS_DELETE_ITEM";
export const STATUS_DELETE_ITEM_SUCCESS = "STATUS_DELETE_ITEM_SUCCESS";
export const STATUS_DELETE_ITEM_ERROR = "STATUS_DELETE_ITEM_ERROR";
export const STATUS_CHANGE_TYPE_MODAL = "STATUS_CHANGE_TYPE_MODAL";

/* HUB */
export const HUB_TOGGLE_MODAL = "HUB_TOGGLE_MODAL";
export const HUB_TOGGLE_DETAIL_MODAL = "HUB_TOGGLE_DETAIL_MODAL";
export const HUB_GET_LIST = "HUB_GET_LIST";
export const HUB_GET_LIST_SUCCESS = "HUB_GET_LIST_SUCCESS";
export const HUB_GET_LIST_ERROR = "HUB_GET_LIST_ERROR";
export const HUB_ADD_ITEM = "HUB_ADD_ITEM";
export const HUB_ADD_ITEM_SUCCESS = "HUB_ADD_ITEM_SUCCESS";
export const HUB_ADD_ITEM_ERROR = "HUB_ADD_ITEM_ERROR";
export const HUB_UPDATE_ITEM = "HUB_UPDATE_ITEM";
export const HUB_UPDATE_ITEM_SUCCESS = "HUB_UPDATE_ITEM_SUCCESS";
export const HUB_UPDATE_ITEM_ERROR = "HUB_UPDATE_ITEM_ERROR";
export const HUB_DELETE_ITEM = "HUB_DELETE_ITEM";
export const HUB_DELETE_ITEM_SUCCESS = "HUB_DELETE_ITEM_SUCCESS";
export const HUB_DELETE_ITEM_ERROR = "HUB_DELETE_ITEM_ERROR";
export const HUB_CHANGE_TYPE_MODAL = "HUB_CHANGE_TYPE_MODAL";
export const HUB_COUNTRY_GET_LIST = "HUB_COUNTRY_GET_LIST";
export const HUB_COUNTRY_GET_LIST_SUCCESS = "HUB_COUNTRY_GET_LIST_SUCCESS";
export const HUB_COUNTRY_GET_LIST_ERROR = "HUB_COUNTRY_GET_LIST_ERROR";
export const HUB_CITY_GET_LIST = "HUB_CITY_GET_LIST";
export const HUB_CITY_GET_LIST_SUCCESS = "HUB_CITY_GET_LIST_SUCCESS";
export const HUB_CITY_GET_LIST_ERROR = "HUB_CITY_GET_LIST_ERROR";

/* BRANCH */
export const BRANCH_TOGGLE_MODAL = "BRANCH_TOGGLE_MODAL";
export const BRANCH_GET_LIST = "BRANCH_GET_LIST";
export const BRANCH_GET_LIST_SUCCESS = "BRANCH_GET_LIST_SUCCESS";
export const BRANCH_GET_LIST_ERROR = "BRANCH_GET_LIST_ERROR";
export const BRANCH_ADD_ITEM = "BRANCH_ADD_ITEM";
export const BRANCH_ADD_ITEM_SUCCESS = "BRANCH_ADD_ITEM_SUCCESS";
export const BRANCH_ADD_ITEM_ERROR = "BRANCH_ADD_ITEM_ERROR";
export const BRANCH_UPDATE_ITEM = "BRANCH_UPDATE_ITEM";
export const BRANCH_UPDATE_ITEM_SUCCESS = "BRANCH_UPDATE_ITEM_SUCCESS";
export const BRANCH_UPDATE_ITEM_ERROR = "BRANCH_UPDATE_ITEM_ERROR";
export const BRANCH_DELETE_ITEM = "BRANCH_DELETE_ITEM";
export const BRANCH_DELETE_ITEM_SUCCESS = "BRANCH_DELETE_ITEM_SUCCESS";
export const BRANCH_DELETE_ITEM_ERROR = "BRANCH_DELETE_ITEM_ERROR";
export const BRANCH_CHANGE_TYPE_MODAL = "BRANCH_CHANGE_TYPE_MODAL";

export const BRANCH_COUNTRY_GET_LIST = "BRANCH_COUNTRY_GET_LIST";
export const BRANCH_COUNTRY_GET_LIST_SUCCESS = "BRANCH_COUNTRY_GET_LIST_SUCCESS";
export const BRANCH_COUNTRY_GET_LIST_ERROR = "BRANCH_COUNTRY_GET_LIST_ERROR";

export const BRANCH_CITY_GET_LIST = "BRANCH_CITY_GET_LIST";
export const BRANCH_CITY_GET_LIST_SUCCESS = "BRANCH_CITY_GET_LIST_SUCCESS";
export const BRANCH_CITY_GET_LIST_ERROR = "BRANCH_CITY_GET_LIST_ERROR";

export const BRANCH_DISTRICT_GET_LIST = "BRANCH_DISTRICT_GET_LIST";
export const BRANCH_DISTRICT_GET_LIST_SUCCESS = "BRANCH_DISTRICT_GET_LIST_SUCCESS";
export const BRANCH_DISTRICT_GET_LIST_ERROR = "BRANCH_DISTRICT_GET_LIST_ERROR";

export const BRANCH_WARD_GET_LIST = "BRANCH_WARD_GET_LIST";
export const BRANCH_WARD_GET_LIST_SUCCESS = "BRANCH_WARD_GET_LIST_SUCCESS";
export const BRANCH_WARD_GET_LIST_ERROR = "BRANCH_WARD_GET_LIST_ERROR";

export const HUB_BRANCH_GET_LIST = "HUB_BRANCH_GET_LIST";
export const HUB_BRANCH_GET_LIST_SUCCESS = "HUB_BRANCH_GET_LIST_SUCCESS";
export const HUB_BRANCH_GET_LIST_ERROR = "HUB_BRANCH_GET_LIST_ERROR";

/* ADDRESS___CODE */
export const CODE_GET_LIST = "CODE_GET_LIST";
export const CODE_GET_LIST_SUCCESS = "CODE_GET_LIST_SUCCESS";
export const CODE_GET_LIST_ERROR = "CODE_GET_LIST_ERROR";

/* ADDRESS___COUNTRY */
export const COUNTRY_TOGGLE_MODAL = "COUNTRY_TOGGLE_MODAL";
export const COUNTRY_GET_LIST = "COUNTRY_GET_LIST";
export const COUNTRY_GET_LIST_SUCCESS = "COUNTRY_GET_LIST_SUCCESS";
export const COUNTRY_GET_LIST_ERROR = "COUNTRY_GET_LIST_ERROR";
export const COUNTRY_ADD_ITEM = "COUNTRY_ADD_ITEM";
export const COUNTRY_ADD_ITEM_SUCCESS = "COUNTRY_ADD_ITEM_SUCCESS";
export const COUNTRY_ADD_ITEM_ERROR = "COUNTRY_ADD_ITEM_ERROR";
export const COUNTRY_UPDATE_ITEM = "COUNTRY_UPDATE_ITEM";
export const COUNTRY_UPDATE_ITEM_SUCCESS = "COUNTRY_UPDATE_ITEM_SUCCESS";
export const COUNTRY_UPDATE_ITEM_ERROR = "COUNTRY_UPDATE_ITEM_ERROR";
export const COUNTRY_DELETE_ITEM = "COUNTRY_DELETE_ITEM";
export const COUNTRY_DELETE_ITEM_SUCCESS = "COUNTRY_DELETE_ITEM_SUCCESS";
export const COUNTRY_DELETE_ITEM_ERROR = "COUNTRY_DELETE_ITEM_ERROR";
export const COUNTRY_CHANGE_TYPE_MODAL = "COUNTRY_CHANGE_TYPE_MODAL";

/* ADDRESS___CITY */
export const CITY_TOGGLE_MODAL = "CITY_TOGGLE_MODAL";
export const CITY_GET_LIST = "CITY_GET_LIST";
export const CITY_GET_LIST_SUCCESS = "CITY_GET_LIST_SUCCESS";
export const CITY_GET_LIST_ERROR = "CITY_GET_LIST_ERROR";
export const CITY_ADD_ITEM = "CITY_ADD_ITEM";
export const CITY_ADD_ITEM_SUCCESS = "CITY_ADD_ITEM_SUCCESS";
export const CITY_ADD_ITEM_ERROR = "CITY_ADD_ITEM_ERROR";
export const CITY_UPDATE_ITEM = "CITY_UPDATE_ITEM";
export const CITY_UPDATE_ITEM_SUCCESS = "CITY_UPDATE_ITEM_SUCCESS";
export const CITY_UPDATE_ITEM_ERROR = "CITY_UPDATE_ITEM_ERROR";
export const CITY_DELETE_ITEM = "CITY_DELETE_ITEM";
export const CITY_DELETE_ITEM_SUCCESS = "CITY_DELETE_ITEM_SUCCESS";
export const CITY_DELETE_ITEM_ERROR = "CITY_DELETE_ITEM_ERROR";
export const CITY_RESET_STATE = "CITY_RESET_STATE";
export const CITY_CHANGE_TYPE_MODAL = "CITY_CHANGE_TYPE_MODAL";

/* ADDRESS___DISTRICT */
export const DISTRICT_TOGGLE_MODAL = "DISTRICT_TOGGLE_MODAL";
export const DISTRICT_GET_LIST = "DISTRICT_GET_LIST";
export const DISTRICT_GET_LIST_SUCCESS = "DISTRICT_GET_LIST_SUCCESS";
export const DISTRICT_GET_LIST_ERROR = "DISTRICT_GET_LIST_ERROR";
export const DISTRICT_ADD_ITEM = "DISTRICT_ADD_ITEM";
export const DISTRICT_ADD_ITEM_SUCCESS = "DISTRICT_ADD_ITEM_SUCCESS";
export const DISTRICT_ADD_ITEM_ERROR = "DISTRICT_ADD_ITEM_ERROR";
export const DISTRICT_UPDATE_ITEM = "DISTRICT_UPDATE_ITEM";
export const DISTRICT_UPDATE_ITEM_SUCCESS = "DISTRICT_UPDATE_ITEM_SUCCESS";
export const DISTRICT_UPDATE_ITEM_ERROR = "DISTRICT_UPDATE_ITEM_ERROR";
export const DISTRICT_DELETE_ITEM = "DISTRICT_DELETE_ITEM";
export const DISTRICT_DELETE_ITEM_SUCCESS = "DISTRICT_DELETE_ITEM_SUCCESS";
export const DISTRICT_DELETE_ITEM_ERROR = "DISTRICT_DELETE_ITEM_ERROR";
export const DISTRICT_RESET_STATE = "DISTRICT_RESET_STATE";
export const DISTRICT_CHANGE_TYPE_MODAL = "DISTRICT_CHANGE_TYPE_MODAL";

/* ADDRESS___WARD */
export const WARD_TOGGLE_MODAL = "WARD_TOGGLE_MODAL";
export const WARD_GET_LIST = "WARD_GET_LIST";
export const WARD_GET_LIST_SUCCESS = "WARD_GET_LIST_SUCCESS";
export const WARD_GET_LIST_ERROR = "WARD_GET_LIST_ERROR";
export const WARD_ADD_ITEM = "WARD_ADD_ITEM";
export const WARD_ADD_ITEM_SUCCESS = "WARD_ADD_ITEM_SUCCESS";
export const WARD_ADD_ITEM_ERROR = "WARD_ADD_ITEM_ERROR";
export const WARD_UPDATE_ITEM = "WARD_UPDATE_ITEM";
export const WARD_UPDATE_ITEM_SUCCESS = "WARD_UPDATE_ITEM_SUCCESS";
export const WARD_UPDATE_ITEM_ERROR = "WARD_UPDATE_ITEM_ERROR";
export const WARD_DELETE_ITEM = "WARD_DELETE_ITEM";
export const WARD_DELETE_ITEM_SUCCESS = "WARD_DELETE_ITEM_SUCCESS";
export const WARD_DELETE_ITEM_ERROR = "WARD_DELETE_ITEM_ERROR";
export const WARD_RESET_STATE = "WARD_RESET_STATE";
export const WARD_CHANGE_TYPE_MODAL = "WARD_CHANGE_TYPE_MODAL";

/* MASTER_DATA --- CARRIER */
export const CARRIER_TOGGLE_MODAL = "CARRIER_TOGGLE_MODAL";
export const CARRIER_GET_LIST = "CARRIER_GET_LIST";
export const CARRIER_GET_LIST_SUCCESS = "CARRIER_GET_LIST_SUCCESS";
export const CARRIER_GET_LIST_ERROR = "CARRIER_GET_LIST_ERROR";
export const CARRIER_CODE_GET_LIST = "CARRIER_CODE_GET_LIST";
export const CARRIER_CODE_GET_LIST_SUCCESS = "CARRIER_CODE_GET_LIST_SUCCESS";
export const CARRIER_CODE_GET_LIST_ERROR = "CARRIER_CODE_GET_LIST_ERROR";
export const CARRIER_ADD_ITEM = "CARRIER_ADD_ITEM";
export const CARRIER_ADD_ITEM_SUCCESS = "CARRIER_ADD_ITEM_SUCCESS";
export const CARRIER_ADD_ITEM_ERROR = "CARRIER_ADD_ITEM_ERROR";
export const CARRIER_UPDATE_ITEM = "CARRIER_UPDATE_ITEM";
export const CARRIER_UPDATE_ITEM_SUCCESS = "CARRIER_UPDATE_ITEM_SUCCESS";
export const CARRIER_UPDATE_ITEM_ERROR = "CARRIER_UPDATE_ITEM_ERROR";
export const CARRIER_DELETE_ITEM = "CARRIER_DELETE_ITEM";
export const CARRIER_DELETE_ITEM_SUCCESS = "CARRIER_DELETE_ITEM_SUCCESS";
export const CARRIER_DELETE_ITEM_ERROR = "CARRIER_DELETE_ITEM_ERROR";
export const CARRIER_CHANGE_TYPE_MODAL = "CARRIER_CHANGE_TYPE_MODAL";
export const CARRIER_GET_CODE_BY_CONDITION = "CARRIER_GET_CODE_BY_CONDITION";
export const CARRIER_GET_CODE_BY_CONDITION_SUCCESS = "CARRIER_GET_CODE_BY_CONDITION_SUCCESS";
export const CARRIER_GET_CODE_BY_CONDITION_ERROR = "CARRIER_GET_CODE_BY_CONDITION_ERROR";

/* SERVICE */
export const SERVICE_TOGGLE_MODAL = "SERVICE_TOGGLE_MODAL";
export const SERVICE_GET_LIST = "SERVICE_GET_LIST";
export const SERVICE_GET_LIST_SUCCESS = "SERVICE_GET_LIST_SUCCESS";
export const SERVICE_GET_LIST_ERROR = "SERVICE_GET_LIST_ERROR";
export const SERVICE_CODE_GET_LIST = "SERVICE_CODE_GET_LIST";
export const SERVICE_CODE_GET_LIST_SUCCESS = "SERVICE_CODE_GET_LIST_SUCCESS";
export const SERVICE_CODE_GET_LIST_ERROR = "SERVICE_CODE_GET_LIST_ERROR";
export const SERVICE_ADD_ITEM = "SERVICE_ADD_ITEM";
export const SERVICE_ADD_ITEM_SUCCESS = "SERVICE_ADD_ITEM_SUCCESS";
export const SERVICE_ADD_ITEM_ERROR = "SERVICE_ADD_ITEM_ERROR";
export const SERVICE_UPDATE_ITEM = "SERVICE_UPDATE_ITEM";
export const SERVICE_UPDATE_ITEM_SUCCESS = "SERVICE_UPDATE_ITEM_SUCCESS";
export const SERVICE_UPDATE_ITEM_ERROR = "SERVICE_UPDATE_ITEM_ERROR";
export const SERVICE_DELETE_ITEM = "SERVICE_DELETE_ITEM";
export const SERVICE_DELETE_ITEM_SUCCESS = "SERVICE_DELETE_ITEM_SUCCESS";
export const SERVICE_DELETE_ITEM_ERROR = "SERVICE_DELETE_ITEM_ERROR";
export const SERVICE_CHANGE_TYPE_MODAL = "SERVICE_CHANGE_TYPE_MODAL";
export const SERVICE_GET_CODE_BY_CONDITION = "SERVICE_GET_CODE_BY_CONDITION";
export const SERVICE_GET_CODE_BY_CONDITION_SUCCESS = "SERVICE_GET_CODE_BY_CONDITION_SUCCESS";
export const SERVICE_GET_CODE_BY_CONDITION_ERROR = "SERVICE_GET_CODE_BY_CONDITION_ERROR";


/* SHIPMENT_TYPE */
export const SHIPMENT_TYPE_TOGGLE_MODAL = "SHIPMENT_TYPE_TOGGLE_MODAL";
export const SHIPMENT_TYPE_GET_LIST = "SHIPMENT_TYPE_GET_LIST";
export const SHIPMENT_TYPE_GET_LIST_SUCCESS = "SHIPMENT_TYPE_GET_LIST_SUCCESS";
export const SHIPMENT_TYPE_GET_LIST_ERROR = "SHIPMENT_TYPE_GET_LIST_ERROR";
export const SHIPMENT_TYPE_CODE_GET_LIST = "SHIPMENT_TYPE_CODE_GET_LIST";
export const SHIPMENT_TYPE_CODE_GET_LIST_SUCCESS = "SHIPMENT_TYPE_CODE_GET_LIST_SUCCESS";
export const SHIPMENT_TYPE_CODE_GET_LIST_ERROR = "SHIPMENT_TYPE_CODE_GET_LIST_ERROR";
export const SHIPMENT_TYPE_ADD_ITEM = "SHIPMENT_TYPE_ADD_ITEM";
export const SHIPMENT_TYPE_ADD_ITEM_SUCCESS = "SHIPMENT_TYPE_ADD_ITEM_SUCCESS";
export const SHIPMENT_TYPE_ADD_ITEM_ERROR = "SHIPMENT_TYPE_ADD_ITEM_ERROR";
export const SHIPMENT_TYPE_UPDATE_ITEM = "SHIPMENT_TYPE_UPDATE_ITEM";
export const SHIPMENT_TYPE_UPDATE_ITEM_SUCCESS = "SHIPMENT_TYPE_UPDATE_ITEM_SUCCESS";
export const SHIPMENT_TYPE_UPDATE_ITEM_ERROR = "SHIPMENT_TYPE_UPDATE_ITEM_ERROR";
export const SHIPMENT_TYPE_DELETE_ITEM = "SHIPMENT_TYPE_DELETE_ITEM";
export const SHIPMENT_TYPE_DELETE_ITEM_SUCCESS = "SHIPMENT_TYPE_DELETE_ITEM_SUCCESS";
export const SHIPMENT_TYPE_DELETE_ITEM_ERROR = "SHIPMENT_TYPE_DELETE_ITEM_ERROR";
export const SHIPMENT_TYPE_CHANGE_TYPE_MODAL = "SHIPMENT_TYPE_CHANGE_TYPE_MODAL";
export const SHIPMENT_TYPE_CARRIER_GET_LIST = "SHIPMENT_TYPE_CARRIER_GET_LIST";
export const SHIPMENT_TYPE_CARRIER_GET_LIST_SUCCESS = "SHIPMENT_TYPE_CARRIER_GET_LIST_SUCCESS";
export const SHIPMENT_TYPE_CARRIER_GET_LIST_ERROR = "SHIPMENT_TYPE_CARRIER_GET_LIST_ERROR";
export const SHIPMENT_TYPE_GET_CODE_BY_CONDITION = "SHIPMENT_TYPE_GET_CODE_BY_CONDITION";
export const SHIPMENT_TYPE_GET_CODE_BY_CONDITION_SUCCESS = "SHIPMENT_TYPE_GET_CODE_BY_CONDITION_SUCCESS";
export const SHIPMENT_TYPE_GET_CODE_BY_CONDITION_ERROR = "SHIPMENT_TYPE_GET_CODE_BY_CONDITION_ERROR";

/* CUSTOMER */
export const CUSTOMER_TOGGLE_MODAL = "CUSTOMER_TOGGLE_MODAL";
export const CUSTOMER_GET_LIST = "CUSTOMER_GET_LIST";
export const CUSTOMER_GET_LIST_SUCCESS = "CUSTOMER_GET_LIST_SUCCESS";
export const CUSTOMER_GET_LIST_ERROR = "CUSTOMER_GET_LIST_ERROR";