/* PRICING SPECIAL */
/* AREA */
export const PRI_SPECIAL_AREA_ERROR = "PRI_SPECIAL_AREA_ERROR";
export const PRI_SPECIAL_AREA_TOGGLE_MODAL = "PRI_SPECIAL_AREA_TOGGLE_MODAL";
export const PRI_SPECIAL_AREA_CHANGE_TYPE_MODAL = "PRI_SPECIAL_AREA_CHANGE_TYPE_MODAL";

export const PRI_SPECIAL_AREA_GET_LIST = "PRI_SPECIAL_AREA_GET_LIST";
export const PRI_SPECIAL_AREA_GET_LIST_SUCCESS = "PRI_SPECIAL_AREA_GET_LIST_SUCCESS";

export const PRI_SPECIAL_AREA_GET_LIST_CITY = "PRI_SPECIAL_AREA_GET_LIST_CITY";
export const PRI_SPECIAL_AREA_GET_LIST_CITY_SUCCESS = "PRI_SPECIAL_AREA_GET_LIST_CITY_SUCCESS";

export const PRI_SPECIAL_AREA_ADD_ITEM = "PRI_SPECIAL_AREA_ADD_ITEM";
export const PRI_SPECIAL_AREA_ADD_ITEM_SUCCESS = "PRI_SPECIAL_AREA_ADD_ITEM_SUCCESS";

export const PRI_SPECIAL_AREA_UPDATE_ITEM = "PRI_SPECIAL_AREA_UPDATE_ITEM";
export const PRI_SPECIAL_AREA_UPDATE_ITEM_SUCCESS = "PRI_SPECIAL_AREA_UPDATE_ITEM_SUCCESS";

export const PRI_SPECIAL_AREA_DELETE_ITEM = "PRI_SPECIAL_AREA_DELETE_ITEM";
export const PRI_SPECIAL_AREA_DELETE_ITEM_SUCCESS = "PRI_SPECIAL_AREA_DELETE_ITEM_SUCCESS";

/* ZONE */
export const PRI_SPECIAL_ZONE_ERROR = "PRI_SPECIAL_ZONE_ERROR";
export const PRI_SPECIAL_ZONE_TOGGLE_MODAL = "PRI_SPECIAL_ZONE_TOGGLE_MODAL";
export const PRI_SPECIAL_ZONE_CHANGE_TYPE_MODAL = "PRI_SPECIAL_ZONE_CHANGE_TYPE_MODAL";

export const PRI_SPECIAL_ZONE_GET_LIST = "PRI_SPECIAL_ZONE_GET_LIST";
export const PRI_SPECIAL_ZONE_GET_LIST_SUCCESS = "PRI_SPECIAL_ZONE_GET_LIST_SUCCESS";

export const PRI_SPECIAL_ZONE_ADD_ITEM = "PRI_SPECIAL_ZONE_ADD_ITEM";
export const PRI_SPECIAL_ZONE_ADD_ITEM_SUCCESS = "PRI_SPECIAL_ZONE_ADD_ITEM_SUCCESS";

export const PRI_SPECIAL_ZONE_UPDATE_ITEM = "PRI_SPECIAL_ZONE_UPDATE_ITEM";
export const PRI_SPECIAL_ZONE_UPDATE_ITEM_SUCCESS = "PRI_SPECIAL_ZONE_UPDATE_ITEM_SUCCESS";

export const PRI_SPECIAL_ZONE_DELETE_ITEM = "PRI_SPECIAL_ZONE_DELETE_ITEM";
export const PRI_SPECIAL_ZONE_DELETE_ITEM_SUCCESS = "PRI_SPECIAL_ZONE_DELETE_ITEM_SUCCESS";

/* CUSTOMER */
export const PRI_SPECIAL_CUSTOMER_ERROR = "PRI_SPECIAL_CUSTOMER_ERROR";
export const PRI_SPECIAL_CUSTOMER_GET_LIST = "PRI_SPECIAL_CUSTOMER_GET_LIST";
export const PRI_SPECIAL_CUSTOMER_GET_LIST_SUCCESS = "PRI_SPECIAL_CUSTOMER_GET_LIST_SUCCESS";

/* CITY */
export const PRI_SPECIAL_CITY_ERROR = "PRI_SPECIAL_CITY_ERROR";

export const PRI_SPECIAL_ORIGIN_CITY_GET_LIST = "PRI_SPECIAL_ORIGIN_CITY_GET_LIST";
export const PRI_SPECIAL_ORIGIN_CITY_GET_LIST_SUCCESS = "PRI_SPECIAL_ORIGIN_CITY_GET_LIST_SUCCESS";
export const PRI_SPECIAL_ORIGIN_CITY_RESET_STATE = "PRI_SPECIAL_ORIGIN_CITY_RESET_STATE";

export const PRI_SPECIAL_DESTINATION_CITY_GET_LIST = "PRI_SPECIAL_DESTINATION_CITY_GET_LIST";
export const PRI_SPECIAL_DESTINATION_CITY_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_CITY_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_CITY_RESET_STATE = "PRI_SPECIAL_DESTINATION_CITY_RESET_STATE";

/* DISTRICT */
export const PRI_SPECIAL_DISTRICT_ERROR = "PRI_SPECIAL_DISTRICT_ERROR";

export const PRI_SPECIAL_DESTINATION_DISTRICT_GET_LIST = "PRI_SPECIAL_DESTINATION_DISTRICT_GET_LIST";
export const PRI_SPECIAL_DESTINATION_DISTRICT_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_DISTRICT_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_DISTRICT_RESET_STATE = "PRI_SPECIAL_DESTINATION_DISTRICT_RESET_STATE";

export const PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_GET_LIST = "PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_GET_LIST";
export const PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_RESET_STATE = "PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_RESET_STATE";

/* WARD */
export const PRI_SPECIAL_WARD_ERROR = "PRI_SPECIAL_WARD_ERROR";

export const PRI_SPECIAL_DESTINATION_WARD_GET_LIST = "PRI_SPECIAL_DESTINATION_WARD_GET_LIST";
export const PRI_SPECIAL_DESTINATION_WARD_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_WARD_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_WARD_RESET_STATE = "PRI_SPECIAL_DESTINATION_WARD_RESET_STATE";

export const PRI_SPECIAL_DESTINATION_WARD_CREATE_GET_LIST = "PRI_SPECIAL_DESTINATION_WARD_CREATE_GET_LIST";
export const PRI_SPECIAL_DESTINATION_WARD_CREATE_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_WARD_CREATE_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_WARD_CREATE_RESET_STATE = "PRI_SPECIAL_DESTINATION_WARD_CREATE_RESET_STATE";

/* UPLOAD */
export const PRI_SPECIAL_UPLOAD_REQUEST = "PRI_SPECIAL_UPLOAD_REQUEST";
export const PRI_SPECIAL_UPLOAD_PROGRESS = "PRI_SPECIAL_UPLOAD_PROGRESS";
export const PRI_SPECIAL_UPLOAD_SUCCESS = "PRI_SPECIAL_UPLOAD_SUCCESS";
export const PRI_SPECIAL_UPLOAD_FAILURE = "PRI_SPECIAL_UPLOAD_FAILURE";

/* END PRICING SPECIAL */
