/* PRICING SPECIAL */
/* AREA */
export const PRI_SPECIAL_AREA_ERROR = "PRI_SPECIAL_AREA_ERROR";
export const PRI_SPECIAL_AREA_TOGGLE_MODAL = "PRI_SPECIAL_AREA_TOGGLE_MODAL";
export const PRI_SPECIAL_AREA_CHANGE_TYPE_MODAL = "PRI_SPECIAL_AREA_CHANGE_TYPE_MODAL";

export const PRI_SPECIAL_AREA_GET_LIST = "PRI_SPECIAL_AREA_GET_LIST";
export const PRI_SPECIAL_AREA_GET_LIST_SUCCESS = "PRI_SPECIAL_AREA_GET_LIST_SUCCESS";

export const PRI_SPECIAL_AREA_GET_LIST_CITY = "PRI_SPECIAL_AREA_GET_LIST_CITY";
export const PRI_SPECIAL_AREA_GET_LIST_CITY_SUCCESS = "PRI_SPECIAL_AREA_GET_LIST_CITY_SUCCESS";

export const PRI_SPECIAL_AREA_ADD_ITEM = "PRI_SPECIAL_AREA_ADD_ITEM";
export const PRI_SPECIAL_AREA_ADD_ITEM_SUCCESS = "PRI_SPECIAL_AREA_ADD_ITEM_SUCCESS";

export const PRI_SPECIAL_AREA_UPDATE_ITEM = "PRI_SPECIAL_AREA_UPDATE_ITEM";
export const PRI_SPECIAL_AREA_UPDATE_ITEM_SUCCESS = "PRI_SPECIAL_AREA_UPDATE_ITEM_SUCCESS";

export const PRI_SPECIAL_AREA_DELETE_ITEM = "PRI_SPECIAL_AREA_DELETE_ITEM";
export const PRI_SPECIAL_AREA_DELETE_ITEM_SUCCESS = "PRI_SPECIAL_AREA_DELETE_ITEM_SUCCESS";

/* ZONE */
export const PRI_SPECIAL_ZONE_ERROR = "PRI_SPECIAL_ZONE_ERROR";
export const PRI_SPECIAL_ZONE_TOGGLE_MODAL = "PRI_SPECIAL_ZONE_TOGGLE_MODAL";
export const PRI_SPECIAL_ZONE_CHANGE_TYPE_MODAL = "PRI_SPECIAL_ZONE_CHANGE_TYPE_MODAL";

export const PRI_SPECIAL_ZONE_GET_LIST = "PRI_SPECIAL_ZONE_GET_LIST";
export const PRI_SPECIAL_ZONE_GET_LIST_SUCCESS = "PRI_SPECIAL_ZONE_GET_LIST_SUCCESS";

export const PRI_SPECIAL_ZONE_ADD_ITEM = "PRI_SPECIAL_ZONE_ADD_ITEM";
export const PRI_SPECIAL_ZONE_ADD_ITEM_SUCCESS = "PRI_SPECIAL_ZONE_ADD_ITEM_SUCCESS";

export const PRI_SPECIAL_ZONE_UPDATE_ITEM = "PRI_SPECIAL_ZONE_UPDATE_ITEM";
export const PRI_SPECIAL_ZONE_UPDATE_ITEM_SUCCESS = "PRI_SPECIAL_ZONE_UPDATE_ITEM_SUCCESS";

export const PRI_SPECIAL_ZONE_DELETE_ITEM = "PRI_SPECIAL_ZONE_DELETE_ITEM";
export const PRI_SPECIAL_ZONE_DELETE_ITEM_SUCCESS = "PRI_SPECIAL_ZONE_DELETE_ITEM_SUCCESS";

export const PRI_SPECIAL_ZONE_UPLOAD_REQUEST = "PRI_SPECIAL_ZONE_UPLOAD_REQUEST";
export const PRI_SPECIAL_ZONE_UPLOAD_PROGRESS = "PRI_SPECIAL_ZONE_UPLOAD_PROGRESS";
export const PRI_SPECIAL_ZONE_UPLOAD_SUCCESS = "PRI_SPECIAL_ZONE_UPLOAD_SUCCESS";

/* RANGE WEIGHT */
export const PRI_SPECIAL_RANGE_WEIGHT_ERROR = "PRI_SPECIAL_RANGE_WEIGHT_ERROR";

export const PRI_SPECIAL_RANGE_WEIGHT_GET_LIST = "PRI_SPECIAL_RANGE_WEIGHT_GET_LIST";
export const PRI_SPECIAL_RANGE_WEIGHT_GET_LIST_SUCCESS = "PRI_SPECIAL_RANGE_WEIGHT_GET_LIST_SUCCESS";

export const PRI_SPECIAL_RANGE_WEIGHT_GET_LIST_CITY = "PRI_SPECIAL_RANGE_WEIGHT_GET_LIST_CITY";
export const PRI_SPECIAL_RANGE_WEIGHT_GET_LIST_CITY_SUCCESS = "PRI_SPECIAL_RANGE_WEIGHT_GET_LIST_CITY_SUCCESS";

export const PRI_SPECIAL_RANGE_WEIGHT_ADD_ITEM = "PRI_SPECIAL_RANGE_WEIGHT_ADD_ITEM";
export const PRI_SPECIAL_RANGE_WEIGHT_ADD_ITEM_SUCCESS = "PRI_SPECIAL_RANGE_WEIGHT_ADD_ITEM_SUCCESS";

export const PRI_SPECIAL_RANGE_WEIGHT_REQUEST_UPDATE_ITEM = "PRI_SPECIAL_RANGE_WEIGHT_REQUEST_UPDATE_ITEM";
export const PRI_SPECIAL_RANGE_WEIGHT_REQUEST_UPDATE_ITEM_SUCCESS = "PRI_SPECIAL_RANGE_WEIGHT_REQUEST_UPDATE_ITEM_SUCCESS";

export const PRI_SPECIAL_RANGE_WEIGHT_UPDATE_ITEM = "PRI_SPECIAL_RANGE_WEIGHT_UPDATE_ITEM";
export const PRI_SPECIAL_RANGE_WEIGHT_UPDATE_ITEM_SUCCESS = "PRI_SPECIAL_RANGE_WEIGHT_UPDATE_ITEM_SUCCESS";

export const PRI_SPECIAL_RANGE_WEIGHT_DELETE_ITEM = "PRI_SPECIAL_RANGE_WEIGHT_DELETE_ITEM";
export const PRI_SPECIAL_RANGE_WEIGHT_DELETE_ITEM_SUCCESS = "PRI_SPECIAL_RANGE_WEIGHT_DELETE_ITEM_SUCCESS";

export const PRI_SPECIAL_RANGE_WEIGHT_UPLOAD_REQUEST = "PRI_SPECIAL_RANGE_WEIGHT_UPLOAD_REQUEST";
export const PRI_SPECIAL_RANGE_WEIGHT_UPLOAD_PROGRESS = "PRI_SPECIAL_RANGE_WEIGHT_UPLOAD_PROGRESS";
export const PRI_SPECIAL_RANGE_WEIGHT_UPLOAD_SUCCESS = "PRI_SPECIAL_RANGE_WEIGHT_UPLOAD_SUCCESS";

/* PRICING */
export const PRI_SPECIAL_PRICING_ERROR = "PRI_SPECIAL_PRICING_ERROR";

export const PRI_SPECIAL_PRICING_GET_LIST = "PRI_SPECIAL_PRICING_GET_LIST";
export const PRI_SPECIAL_PRICING_GET_LIST_SUCCESS = "PRI_SPECIAL_PRICING_GET_LIST_SUCCESS";

export const PRI_SPECIAL_PRICING_ADD_ITEM = "PRI_SPECIAL_PRICING_ADD_ITEM";
export const PRI_SPECIAL_PRICING_ADD_ITEM_SUCCESS = "PRI_SPECIAL_PRICING_ADD_ITEM_SUCCESS";

export const PRI_SPECIAL_PRICING_REQUEST_UPDATE_ITEM = "PRI_SPECIAL_PRICING_REQUEST_UPDATE_ITEM";
export const PRI_SPECIAL_PRICING_REQUEST_UPDATE_ITEM_SUCCESS = "PRI_SPECIAL_PRICING_REQUEST_UPDATE_ITEM_SUCCESS";

export const PRI_SPECIAL_PRICING_UPDATE_ITEM = "PRI_SPECIAL_PRICING_UPDATE_ITEM";
export const PRI_SPECIAL_PRICING_UPDATE_ITEM_SUCCESS = "PRI_SPECIAL_PRICING_UPDATE_ITEM_SUCCESS";

export const PRI_SPECIAL_PRICING_DELETE_ITEM = "PRI_SPECIAL_PRICING_DELETE_ITEM";
export const PRI_SPECIAL_PRICING_DELETE_ITEM_SUCCESS = "PRI_SPECIAL_PRICING_DELETE_ITEM_SUCCESS";

export const PRI_SPECIAL_PRICING_GET_DATA = "PRI_SPECIAL_PRICING_GET_DATA";
export const PRI_SPECIAL_PRICING_GET_DATA_SUCCESS = "PRI_SPECIAL_PRICING_GET_DATA_SUCCESS";

export const PRI_SPECIAL_PRICING_ADD_RANGE_WEIGHT_VALUE = "PRI_SPECIAL_PRICING_ADD_RANGE_WEIGHT_VALUE";
export const PRI_SPECIAL_PRICING_ADD_RANGE_WEIGHT_VALUE_SUCCESS = "PRI_SPECIAL_PRICING_ADD_RANGE_WEIGHT_VALUE_SUCCESS";

export const PRI_SPECIAL_PRICING_GET_VAS = "PRI_SPECIAL_PRICING_GET_VAS";
export const PRI_SPECIAL_PRICING_GET_VAS_SUCCESS = "PRI_SPECIAL_PRICING_GET_VAS_SUCCESS";

export const PRI_SPECIAL_PRICING_UPDATE_VAS = "PRI_SPECIAL_PRICING_UPDATE_VAS";
export const PRI_SPECIAL_PRICING_UPDATE_VAS_SUCCESS = "PRI_SPECIAL_PRICING_UPDATE_VAS_SUCCESS";

export const PRI_SPECIAL_PRICING_GET_FIELD_VAS = "PRI_SPECIAL_PRICING_GET_FIELD_VAS";
export const PRI_SPECIAL_PRICING_GET_FIELD_VAS_SUCCESS = "PRI_SPECIAL_PRICING_GET_FIELD_VAS_SUCCESS";

/* CUSTOMER */
export const PRI_SPECIAL_CUSTOMER_ERROR = "PRI_SPECIAL_CUSTOMER_ERROR";
export const PRI_SPECIAL_CUSTOMER_GET_LIST = "PRI_SPECIAL_CUSTOMER_GET_LIST";
export const PRI_SPECIAL_CUSTOMER_GET_LIST_SUCCESS = "PRI_SPECIAL_CUSTOMER_GET_LIST_SUCCESS";

/* APPROVED BY */
export const PRI_SPECIAL_APPROVED_BY_ERROR = "PRI_SPECIAL_APPROVED_BY_ERROR";
export const PRI_SPECIAL_APPROVED_BY_GET_LIST = "PRI_SPECIAL_APPROVED_BY_GET_LIST";
export const PRI_SPECIAL_APPROVED_BY_GET_LIST_SUCCESS = "PRI_SPECIAL_APPROVED_BY_GET_LIST_SUCCESS";

/* SALEMAN */
export const PRI_SPECIAL_SALEMAN_ERROR = "PRI_SPECIAL_SALEMAN_ERROR";
export const PRI_SPECIAL_SALEMAN_GET_LIST = "PRI_SPECIAL_SALEMAN_GET_LIST";
export const PRI_SPECIAL_SALEMAN_GET_LIST_SUCCESS = "PRI_SPECIAL_SALEMAN_GET_LIST_SUCCESS";

/* CARRIER */
export const PRI_SPECIAL_CARRIER_ERROR = "PRI_SPECIAL_CARRIER_ERROR";
export const PRI_SPECIAL_CARRIER_GET_LIST = "PRI_SPECIAL_CARRIER_GET_LIST";
export const PRI_SPECIAL_CARRIER_GET_LIST_SUCCESS = "PRI_SPECIAL_CARRIER_GET_LIST_SUCCESS";

/* SERVICE */
export const PRI_SPECIAL_SERVICE_ERROR = "PRI_SPECIAL_SERVICE_ERROR";
export const PRI_SPECIAL_SERVICE_GET_LIST = "PRI_SPECIAL_SERVICE_GET_LIST";
export const PRI_SPECIAL_SERVICE_GET_LIST_SUCCESS = "PRI_SPECIAL_SERVICE_GET_LIST_SUCCESS";

/* SHIPMENT TYPE */
export const PRI_SPECIAL_SHIPMENT_TYPE_ERROR = "PRI_SPECIAL_SHIPMENT_TYPE_ERROR";
export const PRI_SPECIAL_SHIPMENT_TYPE_GET_LIST = "PRI_SPECIAL_SHIPMENT_TYPE_GET_LIST";
export const PRI_SPECIAL_SHIPMENT_TYPE_GET_LIST_SUCCESS = "PRI_SPECIAL_SHIPMENT_TYPE_GET_LIST_SUCCESS";

/* CITY */
export const PRI_SPECIAL_CITY_ERROR = "PRI_SPECIAL_CITY_ERROR";

export const PRI_SPECIAL_ORIGIN_CITY_GET_LIST = "PRI_SPECIAL_ORIGIN_CITY_GET_LIST";
export const PRI_SPECIAL_ORIGIN_CITY_GET_LIST_SUCCESS = "PRI_SPECIAL_ORIGIN_CITY_GET_LIST_SUCCESS";
export const PRI_SPECIAL_ORIGIN_CITY_RESET_STATE = "PRI_SPECIAL_ORIGIN_CITY_RESET_STATE";

export const PRI_SPECIAL_DESTINATION_CITY_GET_LIST = "PRI_SPECIAL_DESTINATION_CITY_GET_LIST";
export const PRI_SPECIAL_DESTINATION_CITY_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_CITY_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_CITY_RESET_STATE = "PRI_SPECIAL_DESTINATION_CITY_RESET_STATE";

/* DISTRICT */
export const PRI_SPECIAL_DISTRICT_ERROR = "PRI_SPECIAL_DISTRICT_ERROR";

export const PRI_SPECIAL_DESTINATION_DISTRICT_GET_LIST = "PRI_SPECIAL_DESTINATION_DISTRICT_GET_LIST";
export const PRI_SPECIAL_DESTINATION_DISTRICT_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_DISTRICT_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_DISTRICT_RESET_STATE = "PRI_SPECIAL_DESTINATION_DISTRICT_RESET_STATE";

export const PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_GET_LIST = "PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_GET_LIST";
export const PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_RESET_STATE = "PRI_SPECIAL_DESTINATION_DISTRICT_CREATE_RESET_STATE";

/* WARD */
export const PRI_SPECIAL_WARD_ERROR = "PRI_SPECIAL_WARD_ERROR";

export const PRI_SPECIAL_DESTINATION_WARD_GET_LIST = "PRI_SPECIAL_DESTINATION_WARD_GET_LIST";
export const PRI_SPECIAL_DESTINATION_WARD_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_WARD_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_WARD_RESET_STATE = "PRI_SPECIAL_DESTINATION_WARD_RESET_STATE";

export const PRI_SPECIAL_DESTINATION_WARD_CREATE_GET_LIST = "PRI_SPECIAL_DESTINATION_WARD_CREATE_GET_LIST";
export const PRI_SPECIAL_DESTINATION_WARD_CREATE_GET_LIST_SUCCESS = "PRI_SPECIAL_DESTINATION_WARD_CREATE_GET_LIST_SUCCESS";
export const PRI_SPECIAL_DESTINATION_WARD_CREATE_RESET_STATE = "PRI_SPECIAL_DESTINATION_WARD_CREATE_RESET_STATE";

/* UPLOAD */
export const PRI_SPECIAL_UPLOAD_REQUEST = "PRI_SPECIAL_UPLOAD_REQUEST";
export const PRI_SPECIAL_UPLOAD_PROGRESS = "PRI_SPECIAL_UPLOAD_PROGRESS";
export const PRI_SPECIAL_UPLOAD_SUCCESS = "PRI_SPECIAL_UPLOAD_SUCCESS";
export const PRI_SPECIAL_UPLOAD_FAILURE = "PRI_SPECIAL_UPLOAD_FAILURE";

/* END PRICING SPECIAL */
