/* SETTING */
export const CHANGE_SIDEBAR_VISIBILITY = 'CHANGE_SIDEBAR_VISIBILITY';
export const CHANGE_MOBILE_SIDEBAR_VISIBILITY = 'CHANGE_MOBILE_SIDEBAR_VISIBILITY';
export const CHANGE_THEME_TO_DARK = 'CHANGE_THEME_TO_DARK';
export const CHANGE_THEME_TO_DARK_BLUE = 'CHANGE_THEME_TO_DARK_BLUE';
export const CHANGE_THEME_TO_LIGHT = 'CHANGE_THEME_TO_LIGHT';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* ALERT */
export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_DANGER = 'ALERT_DANGER';
export const ALERT_CLEAR = 'ALERT_CLEAR';

/* SYSTEM */
export const SYSTEM_GET_LIST = "SYSTEM_GET_LIST";
export const SYSTEM_GET_LIST_SUCCESS = "SYSTEM_GET_LIST_SUCCESS";
export const SYSTEM_GET_LIST_ERROR = "SYSTEM_GET_LIST_ERROR";
export const SYSTEM_INFO = "SYSTEM_INFO";
export const SYSTEM_INFO_SUCCESS = "SYSTEM_INFO_SUCCESS";

export const SETTING_GET = "SETTING_GET";
export const SETTING_GET_SUCCESS = "SETTING_GET_SUCCESS";
export const SETTING_GET_ERROR = "SETTING_GET_ERROR";
export const GET_SETTING = "GET_SETTING";
export const GET_SETTING_SUCCESS = "GET_SETTING_SUCCESS";
export const GET_SETTING_ERROR = "GET_SETTING_ERROR";
export const UPDATE_SETTING = "UPDATE_SETTING";
export const UPDATE_SETTING_ERROR = "UPDATE_SETTING_ERROR";
export const UPDATE_SETTING_SUCCESS = "UPDATE_SETTING_SUCCESS";
