/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const VERITY_AUTH = 'VERITY_AUTH';
export const VERITY_AUTH_SUCCESS = 'VERITY_AUTH_SUCCESS';

/* USER */
export const USER_TOGGLE_MODAL = "USER_TOGGLE_MODAL";
export const USER_GET_LIST = "USER_GET_LIST";
export const USER_GET_LIST_SUCCESS = "USER_GET_LIST_SUCCESS";
export const USER_GET_LIST_ERROR = "USER_GET_LIST_ERROR";
export const USER_ADD_ITEM = "USER_ADD_ITEM";
export const USER_ADD_ITEM_SUCCESS = "USER_ADD_ITEM_SUCCESS";
export const USER_ADD_ITEM_ERROR = "USER_ADD_ITEM_ERROR";
export const USER_UPDATE_ITEM = "USER_UPDATE_ITEM";
export const USER_UPDATE_ITEM_SUCCESS = "USER_UPDATE_ITEM_SUCCESS";
export const USER_UPDATE_ITEM_ERROR = "USER_UPDATE_ITEM_ERROR";
export const USER_DELETE_ITEM = "USER_DELETE_ITEM";
export const USER_DELETE_ITEM_SUCCESS = "USER_DELETE_ITEM_SUCCESS";
export const USER_DELETE_ITEM_ERROR = "USER_DELETE_ITEM_ERROR";
export const USER_CHANGE_TYPE_MODAL = "USER_CHANGE_TYPE_MODAL";
export const USER_UPLOAD_AVATAR = "USER_UPLOAD_AVATAR";

/* ROLE */
export const ROLE_TOGGLE_MODAL = "ROLE_TOGGLE_MODAL";
export const ROLE_GET_LIST = "ROLE_GET_LIST";
export const ROLE_GET_LIST_ALL = "ROLE_GET_LIST_ALL";
export const ROLE_GET_LIST_SUCCESS = "ROLE_GET_LIST_SUCCESS";
export const ROLE_GET_LIST_ERROR = "ROLE_GET_LIST_ERROR";
export const ROLE_ADD_ITEM = "ROLE_ADD_ITEM";
export const ROLE_ADD_ITEM_SUCCESS = "ROLE_ADD_ITEM_SUCCESS";
export const ROLE_ADD_ITEM_ERROR = "ROLE_ADD_ITEM_ERROR";
export const ROLE_UPDATE_ITEM = "ROLE_UPDATE_ITEM";
export const ROLE_UPDATE_ITEM_SUCCESS = "ROLE_UPDATE_ITEM_SUCCESS";
export const ROLE_UPDATE_ITEM_ERROR = "ROLE_UPDATE_ITEM_ERROR";
export const ROLE_DELETE_ITEM = "ROLE_DELETE_ITEM";
export const ROLE_DELETE_ITEM_SUCCESS = "ROLE_DELETE_ITEM_SUCCESS";
export const ROLE_DELETE_ITEM_ERROR = "ROLE_DELETE_ITEM_ERROR";
export const ROLE_CHANGE_TYPE_MODAL = "ROLE_CHANGE_TYPE_MODAL";

/* PERMISSION */
export const PERMISSION_TOGGLE_MODAL = "PERMISSION_TOGGLE_MODAL";
export const PERMISSION_GET_LIST = "PERMISSION_GET_LIST";
export const PERMISSION_GET_LIST_SUCCESS = "PERMISSION_GET_LIST_SUCCESS";
export const PERMISSION_GET_LIST_ERROR = "PERMISSION_GET_LIST_ERROR";
export const PERMISSION_ADD_ITEM = "PERMISSION_ADD_ITEM";
export const PERMISSION_ADD_ITEM_SUCCESS = "PERMISSION_ADD_ITEM_SUCCESS";
export const PERMISSION_ADD_ITEM_ERROR = "PERMISSION_ADD_ITEM_ERROR";
export const PERMISSION_UPDATE_ITEM = "PERMISSION_UPDATE_ITEM";
export const PERMISSION_UPDATE_ITEM_SUCCESS = "PERMISSION_UPDATE_ITEM_SUCCESS";
export const PERMISSION_UPDATE_ITEM_ERROR = "PERMISSION_UPDATE_ITEM_ERROR";
export const PERMISSION_DELETE_ITEM = "PERMISSION_DELETE_ITEM";
export const PERMISSION_DELETE_ITEM_SUCCESS = "PERMISSION_DELETE_ITEM_SUCCESS";
export const PERMISSION_DELETE_ITEM_ERROR = "PERMISSION_DELETE_ITEM_ERROR";
export const PERMISSION_CHANGE_TYPE_MODAL = "PERMISSION_CHANGE_TYPE_MODAL";