/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* ALERT */
export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_DANGER = 'ALERT_DANGER';
export const ALERT_CLEAR = 'ALERT_CLEAR';

/* MODAL */
export const MODAL_TOGGLE = 'MODAL_TOGGLE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

/* MASTER_DATA --- STATUS */
export const STATUS_TOGGLE_MODAL = "STATUS_TOGGLE_MODAL";
export const STATUS_GET_LIST = "STATUS_GET_LIST";
export const STATUS_GET_LIST_SUCCESS = "STATUS_GET_LIST_SUCCESS";
export const STATUS_GET_LIST_ERROR = "STATUS_GET_LIST_ERROR";
export const STATUS_ADD_ITEM = "STATUS_ADD_ITEM";
export const STATUS_ADD_ITEM_SUCCESS = "STATUS_ADD_ITEM_SUCCESS";
export const STATUS_ADD_ITEM_ERROR = "STATUS_ADD_ITEM_ERROR";
export const STATUS_UPDATE_ITEM = "STATUS_UPDATE_ITEM";
export const STATUS_UPDATE_ITEM_SUCCESS = "STATUS_UPDATE_ITEM_SUCCESS";
export const STATUS_UPDATE_ITEM_ERROR = "STATUS_UPDATE_ITEM_ERROR";
export const STATUS_DELETE_ITEM = "STATUS_DELETE_ITEM";
export const STATUS_DELETE_ITEM_SUCCESS = "STATUS_DELETE_ITEM_SUCCESS";
export const STATUS_DELETE_ITEM_ERROR = "STATUS_DELETE_ITEM_ERROR";

/* MASTER_DATA --- HUB */
export const HUB_TOGGLE_MODAL = "HUB_TOGGLE_MODAL";
export const HUB_GET_LIST = "HUB_GET_LIST";
export const HUB_GET_LIST_SUCCESS = "HUB_GET_LIST_SUCCESS";
export const HUB_GET_LIST_ERROR = "HUB_GET_LIST_ERROR";
export const HUB_ADD_ITEM = "HUB_ADD_ITEM";
export const HUB_ADD_ITEM_SUCCESS = "HUB_ADD_ITEM_SUCCESS";
export const HUB_ADD_ITEM_ERROR = "HUB_ADD_ITEM_ERROR";
export const HUB_UPDATE_ITEM = "HUB_UPDATE_ITEM";
export const HUB_UPDATE_ITEM_SUCCESS = "HUB_UPDATE_ITEM_SUCCESS";
export const HUB_UPDATE_ITEM_ERROR = "HUB_UPDATE_ITEM_ERROR";
export const HUB_DELETE_ITEM = "HUB_DELETE_ITEM";
export const HUB_DELETE_ITEM_SUCCESS = "HUB_DELETE_ITEM_SUCCESS";
export const HUB_DELETE_ITEM_ERROR = "HUB_DELETE_ITEM_ERROR";
export const HUB_GET_LIST_SELECT = "HUB_GET_LIST_SELECT";
export const HUB_GET_LIST_SELECT_SUCCESS = "HUB_GET_LIST_SELECT_SUCCESS";
export const HUB_GET_LIST_SELECT_ERROR = "HUB_GET_LIST_SELECT_ERROR";


/* MASTER_DATA --- BRANCH */
export const BRANCH_TOGGLE_MODAL = "BRANCH_TOGGLE_MODAL";
export const BRANCH_GET_LIST = "BRANCH_GET_LIST";
export const BRANCH_GET_LIST_SUCCESS = "BRANCH_GET_LIST_SUCCESS";
export const BRANCH_GET_LIST_ERROR = "BRANCH_GET_LIST_ERROR";
export const BRANCH_ADD_ITEM = "BRANCH_ADD_ITEM";
export const BRANCH_ADD_ITEM_SUCCESS = "BRANCH_ADD_ITEM_SUCCESS";
export const BRANCH_ADD_ITEM_ERROR = "BRANCH_ADD_ITEM_ERROR";
export const BRANCH_UPDATE_ITEM = "BRANCH_UPDATE_ITEM";
export const BRANCH_UPDATE_ITEM_SUCCESS = "BRANCH_UPDATE_ITEM_SUCCESS";
export const BRANCH_UPDATE_ITEM_ERROR = "BRANCH_UPDATE_ITEM_ERROR";
export const BRANCH_DELETE_ITEM = "BRANCH_DELETE_ITEM";
export const BRANCH_DELETE_ITEM_SUCCESS = "BRANCH_DELETE_ITEM_SUCCESS";
export const BRANCH_DELETE_ITEM_ERROR = "BRANCH_DELETE_ITEM_ERROR";

/* MASTER_DATA --- ADDRESS */
export const ADDRESS_GET_LIST = "ADDRESS_GET_LIST";
export const ADDRESS_GET_LIST_SUCCESS = "ADDRESS_GET_LIST_SUCCESS";
export const ADDRESS_GET_LIST_ERROR = "ADDRESS_GET_LIST_ERROR";
export const ADDRESS_UPDATE_ITEM = "ADDRESS_UPDATE_ITEM";
export const ADDRESS_UPDATE_ITEM_SUCCESS = "ADDRESS_UPDATE_ITEM_SUCCESS";
export const ADDRESS_UPDATE_ITEM_ERROR = "ADDRESS_UPDATE_ITEM_ERROR";

export const COUNTRY_TOGGLE_MODAL = "COUNTRY_TOGGLE_MODAL";
export const COUNTRY_GET_LIST = "COUNTRY_GET_LIST";
export const COUNTRY_GET_LIST_SUCCESS = "COUNTRY_GET_LIST_SUCCESS";
export const COUNTRY_GET_LIST_ERROR = "COUNTRY_GET_LIST_ERROR";
export const COUNTRY_ADD_ITEM = "COUNTRY_ADD_ITEM";
export const COUNTRY_ADD_ITEM_SUCCESS = "COUNTRY_ADD_ITEM_SUCCESS";
export const COUNTRY_ADD_ITEM_ERROR = "COUNTRY_ADD_ITEM_ERROR";
export const COUNTRY_UPDATE_ITEM = "COUNTRY_UPDATE_ITEM";
export const COUNTRY_UPDATE_ITEM_SUCCESS = "COUNTRY_UPDATE_ITEM_SUCCESS";
export const COUNTRY_UPDATE_ITEM_ERROR = "COUNTRY_UPDATE_ITEM_ERROR";
export const COUNTRY_GET_LIST_SELECT = "COUNTRY_GET_LIST_SELECT";
export const COUNTRY_GET_LIST_SELECT_SUCCESS = "COUNTRY_GET_LIST_SELECT_SUCCESS";
export const COUNTRY_GET_LIST_SELECT_ERROR = "COUNTRY_GET_LIST_SELECT_ERROR";

export const CITY_TOGGLE_MODAL = "CITY_TOGGLE_MODAL";
export const CITY_GET_LIST = "CITY_GET_LIST";
export const CITY_GET_LIST_SUCCESS = "CITY_GET_LIST_SUCCESS";
export const CITY_GET_LIST_ERROR = "CITY_GET_LIST_ERROR";
export const CITY_UPDATE_ITEM = "CITY_UPDATE_ITEM";
export const CITY_UPDATE_ITEM_SUCCESS = "CITY_UPDATE_ITEM_SUCCESS";
export const CITY_UPDATE_ITEM_ERROR = "CITY_UPDATE_ITEM_ERROR";
export const CITY_GET_LIST_SELECT = "CITY_GET_LIST_SELECT";
export const CITY_GET_LIST_SELECT_SUCCESS = "CITY_GET_LIST_SELECT_SUCCESS";
export const CITY_GET_LIST_SELECT_ERROR = "CITY_GET_LIST_SELECT_ERROR";

export const DISTRICT_GET_LIST = "DISTRICT_GET_LIST";
export const DISTRICT_GET_LIST_SUCCESS = "DISTRICT_GET_LIST_SUCCESS";
export const DISTRICT_GET_LIST_ERROR = "DISTRICT_GET_LIST_ERROR";
export const DISTRICT_UPDATE_ITEM = "DISTRICT_UPDATE_ITEM";
export const DISTRICT_UPDATE_ITEM_SUCCESS = "DISTRICT_UPDATE_ITEM_SUCCESS";
export const DISTRICT_UPDATE_ITEM_ERROR = "DISTRICT_UPDATE_ITEM_ERROR";
export const DISTRICT_TOGGLE_MODAL = "STATUS_TOGGLE_MODAL";
export const DISTRICT_GET_LIST_SELECT = "DISTRICT_GET_LIST_SELECT";
export const DISTRICT_GET_LIST_SELECT_SUCCESS = "DISTRICT_GET_LIST_SELECT_SUCCESS";
export const DISTRICT_GET_LIST_SELECT_ERROR = "DISTRICT_GET_LIST_SELECT_ERROR";

export const WARD_GET_LIST = "WARD_GET_LIST";
export const WARD_GET_LIST_SUCCESS = "WARD_GET_LIST_SUCCESS";
export const WARD_GET_LIST_ERROR = "WARD_GET_LIST_ERROR";
export const WARD_UPDATE_ITEM = "WARD_UPDATE_ITEM";
export const WARD_UPDATE_ITEM_SUCCESS = "WARD_UPDATE_ITEM_SUCCESS";
export const WARD_UPDATE_ITEM_ERROR = "WARD_UPDATE_ITEM_ERROR";
export const WARD_GET_LIST_SELECT = "WARD_GET_LIST_SELECT";
export const WARD_GET_LIST_SELECT_SUCCESS = "WARD_GET_LIST_SELECT_SUCCESS";
export const WARD_GET_LIST_SELECT_ERROR = "WARD_GET_LIST_SELECT_ERROR";

