/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* ALERT */
export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_DANGER = 'ALERT_DANGER';
export const ALERT_CLEAR = 'ALERT_CLEAR';

/* MODAL */
export const MODAL_TOGGLE = 'MODAL_TOGGLE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

/* MASTER_DATA --- STATUS */
export const STATUS_TOGGLE_MODAL = "STATUS_TOGGLE_MODAL";
export const STATUS_GET_LIST = "STATUS_GET_LIST";
export const STATUS_GET_LIST_SUCCESS = "STATUS_GET_LIST_SUCCESS";
export const STATUS_GET_LIST_ERROR = "STATUS_GET_LIST_ERROR";
export const STATUS_ADD_ITEM = "STATUS_ADD_ITEM";
export const STATUS_ADD_ITEM_SUCCESS = "STATUS_ADD_ITEM_SUCCESS";
export const STATUS_ADD_ITEM_ERROR = "STATUS_ADD_ITEM_ERROR";
export const STATUS_UPDATE_ITEM = "STATUS_UPDATE_ITEM";
export const STATUS_UPDATE_ITEM_SUCCESS = "STATUS_UPDATE_ITEM_SUCCESS";
export const STATUS_UPDATE_ITEM_ERROR = "STATUS_UPDATE_ITEM_ERROR";
export const STATUS_DELETE_ITEM = "STATUS_DELETE_ITEM";
export const STATUS_DELETE_ITEM_SUCCESS = "STATUS_DELETE_ITEM_SUCCESS";
export const STATUS_DELETE_ITEM_ERROR = "STATUS_DELETE_ITEM_ERROR";


